"""Regenerate Pygments stylesheets for the light/dark themes."""

from pathlib import Path

from pygments.formatters import HtmlFormatter

CSS_DIR = Path(__file__).resolve().parent.parent / "app" / "static" / "css"


def main():
    header = "/* generated by scripts/generate_pygments_css.py */\n"
    light = HtmlFormatter(style="default", nobackground=True).get_style_defs(
        ".highlight"
    )
    dark = HtmlFormatter(style="monokai", nobackground=True).get_style_defs(
        '[data-theme="dark"] .highlight'
    )
    (CSS_DIR / "pygments-light.css").write_text(
        header + light + "\n", encoding="utf-8"
    )
    (CSS_DIR / "pygments-dark.css").write_text(
        header + dark + "\n", encoding="utf-8"
    )
    print("written:", CSS_DIR)


if __name__ == "__main__":
    main()
